// Copyright 2025 JesusTouchMe

#ifndef JESUSVM_FRAMEWORK_INCLUDE_JESUSVM_PLATFORM_MEMORY_H
#define JESUSVM_FRAMEWORK_INCLUDE_JESUSVM_PLATFORM_MEMORY_H 1

#include <cstddef>

namespace Platform {
    std::size_t GetUsedMemory();
}

#endif // JESUSVM_FRAMEWORK_INCLUDE_JESUSVM_PLATFORM_MEMORY_H
