// Copyright 2025 JesusTouchMe

#ifndef JESUSVM_FRAMEWORK_INCLUDE_JESUSVM_OPTIONS_H
#define JESUSVM_FRAMEWORK_INCLUDE_JESUSVM_OPTIONS_H 1

#include "types.h"

namespace JesusVM::opt {
    constexpr bool gcProfilerEnabled = true;

    constexpr u64 MIN_THREADS = 6;
    constexpr u64 MAX_CONCURRENT_THREADS = 50;

    constexpr u64 MIN_THREADS_FOR_FILLED_EVENT_QUEUE = 12;
    constexpr u64 MIN_EVENT_QUEUE_SIZE_BEFORE_THREAD_LAUNCH = 4;
    constexpr u64 MAX_THREADS_FOR_QUEUED_FUNCTIONS = 24;
    constexpr u64 EVENT_QUEUE_THREAD_RATIO_THRESHOLD = 2;

    constexpr u64 MIN_VTHREADS = 2;
    constexpr u64 MAX_VTHREADS = 20;
    constexpr u64 VTHREAD_GROUP_LAUNCH_THRESHOLD = 10;

    constexpr u64 SMALL_FUNCTION_BYTECODE_THRESHOLD = 50;
    constexpr u64 PURE_FUNCTION_BYTECODE_THRESHOLD = 20;
}

#endif // JESUSVM_FRAMEWORK_INCLUDE_JESUSVM_OPTIONS_H
